### ISSUE TITLE
Prototype fixes from March 5 user session

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#103]
**DIRECTOR SEARCH (CorpParty Flow)**
xd link: https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/

DIRECTOR SEARCH:
- [x] Remove "Clear" buttons next to input fields; users would rather just highlight and replace text (I haven't updated the mockups for this yet but I will :) )
- [x] Allow user to skip "Remove" buttons press "Tab" key between grey dropdown/input fields
- [x] Allow users to search by Company Status (Act/His data)

DIRECTOR SEARCH RESULTS TABLE:
- [x] The order of the first four columns, from left to right, should be "Filing #", "Last Name", **"First Name"**, **"Middle Name"**
- [x] Show "Office Held" column (currently missing in prototype; see mockups)
- [x] BUG? There are problems sorting by "Inc/Reg #" column
- [x] "Status" (Act/His) column renamed to "Company Status" (I haven't updated the mockups for this yet but I will :) )
- [x] "Company Name" column needs to be in table (see mockups). This is the DEFAULT column that shows up (as opposed to "Company Status" (Act/His) or "Address". i will be updating the mockups to give this as the default toggle option above the table.
- [x] Allow user to highlight the text in the row without it registering as a click and sending them to Details Page
- [x] Sort director search results by Last Name by default

DIRECTOR DETAILS PAGE:
- [x] In the "Other instances of..." tables on the right, the column titled "Filing Address" should be renamed "Address" (I haven't updated the mockups for this yet but I will :) )
- [x] Please add more padding between the group of text on the left and the ones on the right (right now they're a little too close, which makes them look crammed; see mockups)
- [x] Change page title to "[Person] at [Company Name]", and company name should link to Corporation detail page

**CORPORATION SEARCH (Corporation Flow)**
xd link: https://xd.adobe.com/view/aca71ede-6709-42d3-74d8-76c31a94b1e5-da96/

CORPORATION SEARCH PAGE:
- [x] Change suggested text from "John Smith" to prompt text that says "Corporation Name or Number" - I think this is better as an instruction than a fake company name

Note: I will also be updating the above xd links with some new requests from users, over the next few days. I will document those in another Issue :)

**Comment by syin** [comment]
> Allow user to highlight the text in the row without it registering as a click and sending them to Details Page
Does this mean the entire row shouldn't link to the detail page, and instead maybe the filing # column should look like a hyperlink?

**Comment by byshine** [comment]
@syin ` Allow users to search by Company Status (Act/His data)`
