### ISSUE TITLE
Director Search UI Prototype

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#11]
based on mockups from @jvanoyen

**Comment by countable** [comment]
We should generate a frontend folder with vue-cli, based on vuetfy

**Comment by countable** [comment]
@pwei1018 was it you that mentioned a Vue template your team uses?

**Comment by countable** [comment]
Analogous Front-end here. https://github.com/bcgov/lear/tree/master/coops-ui

**Comment by pwei1018** [comment]
We also have auth front-end here. https://github.com/bcgov/sbc-auth/tree/development/auth-web
