### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#119]
When loading the page, there is a 404 ajax call to http://localhost/api/v1/users/3b6a6e90-b248-4e32-a0d2-d2cc1b6332c4/settings

Please determine why this is and remove/resolve.

**Comment by byshine** [comment]
Fixed by setting the auth root api url to their dev keycloack
https://auth-api-dev.pathfinder.gov.bc.ca/api/v1

WIll need to be changed for prod.
