### ISSUE TITLE
Iterate on mockup drafts 

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#12]
1. Tables (including pagination) (https://vuetifyjs.com/en/components/data-tables#data-tables)
2. Text Inputs (https://vuetifyjs.com/en/components/text-fields)
- We are leveraging the 'filled' variant here (you can simply set the prop on the component as 'filled' to leverage this)
3. I've attached the MVP staff search (see below) - this work flow is in it's infancy, however this is how we've implemented a simple search field for this interface

![staff-search-page.png](https://images.zenhubusercontent.com/5e0e4a0a021f7a328c95da84/22d60424-49ef-465a-acf3-7755723cec25)

**Comment by jvanoyen** [comment]
The first part of the Director Search flow: https://xd.adobe.com/view/2eed52e2-4e26-42dc-4dbc-dd96295722ec-58dc/ - you can click through to see the log in, manage and products dropdown, which then brings you to the first pages of the director search.

It is directly modelled from the BCSC log in and manage pages.

**Comment by countable** [comment]
@jvanoyen I think we need to provide these to Andrew and Sumesh of the registries team. Let's determine the best medium or card in their boards for it.

**Comment by jvanoyen** [comment]
@countable I also sent in rocket chat, Andrew is reviewing. I could also add to the entities board?

**Comment by countable** [comment]
Yes please :) After the revisions discussed today (copy invite link)
