### ISSUE TITLE
DIRECTOR SEARCH (CorpParty) UI Fixes - 2020-04-02

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#126]
Screencastify videos explaining changes...
Styling and Search Page: https://drive.google.com/file/d/10xI78xfLJN8qRZ2FfJoMfxqHupzTG5xP/view
Search Results Table: https://drive.google.com/file/d/1S1zyQlzvkB70-PkuOGIfprZo5HED0YkN/view
Details Page: https://drive.google.com/file/d/1Xi8IN6Hcf3auSS6uB_JxQJZvDJVnhf-m/view
XD link for mockups: https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/

GENERAL STYLING NOTES
- [x] Mockup has been changed to 1280 screen width to address problems between screen sizes
- [x] Remove drop shadows on buttons - the most recent styling shared by Jeremy shows flat, not raised, buttons. 
![Screen Shot 2020-04-02 at 10.28.24 AM.png](https://images.zenhubusercontent.com/5e0e4a0a021f7a328c95da84/e82fa361-d502-456f-99d9-e13e35ecd32c)
- [x] Non-CTA button ("Remove Filter", "+ Add Filter", "Export to xslx.") should have the grey stroke and white fill style as seen in mockup; this differentiates it from the many grey input fields we have in the ui.
- [x] Note changed button text size/styling: All buttons are text size 16px, and CTA buttons (white text on blue bg) are now Bold text

DIRECTOR SEARCH PAGE
- [x] Microcopy in the buttons next to inputs changed from "REMOVE" to "Remove Filter", have a stroke of grey #B0B1B3, text colour grey #5F5F60, and not all caps.
- [x] Search inputs/dropdowns need a lighter grey line along their bottom - use grey #B0B1B3 

DIRECTOR SEARCH RESULTS
- [x] Horizontal scroll bar that is visible on all devices, and all browsers
- [x] Fixed table header which remains visible as user scrolls
- [x] Add pagination to the top right corner of the table as well
- [x] Grey out the row background colour if this row has been selected this session
- [x] Can the hover action be a highlighted outline in grey #5F5F60? 
- [x] Padding between columns has been changed to 32px to use less space
- [x] "Address", "Company Name" and "Company Address" columns are wider than other columns to (as much as possible) allow for a single line of text
- [x] More padding at left and right edges of table (see mockup)

DIRECTOR DETAILS
- [x] The main heading on the white card has been reduced in size to 18px to fit smaller screens better
- [x] The subtitle under that ("Filing #....") has been rduced in size to 14 px
- [x] Small tables to the right ('Other offices held...") have now been bumped to the bottom, below the director and company info
- [x] These small tables should have borders/rows even if there is no content (see mockups for a no content example). Otherwise it looks confusing/messy to change the styling if there is not content vs. if there is.
- [x] These small tables should have a width of 640 px and not stretch all the way across the card
- [x] These small tables' headings have been reduced to size 18px
- [x] These small tables' headings should not be in italics (see mockup)
- [x] There are light grey lines between the bold copy and the unbolded copy in order to add structure to the page, thus improving readbility. Please add into prototype and keep the padding between the bold copy, these lines, and the unbolded copy the same regardless of screen/card size: 
![Screen Shot 2020-04-02 at 11.06.54 AM.png](https://images.zenhubusercontent.com/5e0e4a0a021f7a328c95da84/04e14a24-9abb-4d94-9e6f-0100151d5ae5)
- [x] Line height in this copy should be 30px: 
![Screen Shot 2020-04-02 at 11.07.47 AM.png](https://images.zenhubusercontent.com/5e0e4a0a021f7a328c95da84/da500740-4141-4d17-a8b5-a8cfb4b6ba20)

**Comment by byshine** [comment]
Doing the last two at the end
