### ISSUE TITLE
Error Handling on Front-End, and recovery.

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#134]
Once one operation fails it cascades to a few others.
But the UI shouldnt become unresponsive with DuplicateNavigation errors just because one API call failed. It should retry if the user performs a new operation.

The FE should also report API errors instead of falling back to "no results found". For example, just now I got a "token expired" error for all API calls and had to sign out and sign in to fix it.

**Comment by byshine** [comment]
okie
