### ISSUE TITLE
Warn about high volume search cases.

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#137]
The UI should indicate that a search may be slow, based on any of the following:

for these:
- if nicknames or similar match type is used, should be used in combination. "This search may return many results and be very slow. Add more filters to improve performance."
- if address or postal code search is used, include the same warning.

do not allow searching by:
- company status only. (act/hist)
- address without format: NUMBER SPACE ALPHANUMERICS ie) "123 Sesame" start with: \S+\s\S+
 - empty.
 - don't allow fewer than three characters unless using exact match.

**Comment by byshine** [comment]
done
