### ISSUE TITLE
Assets and Access

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#4]
Get user ID from Bob, for test app
Get SQL for search transaction
Bob will gave names of mainframe users
Connection to Test DB (firewall change)

**Comment by bfbowles** [comment]
Julie I sent you a email this morning with the userid and url for virtel.  Give me a phone call 250 356-8681 will give you the password and explain how to sign on .

**Comment by countable** [comment]
Thanks @bfbowles !

May I have a dump of the `dev` database and SQL example?
