### ISSUE TITLE
Prototype UI Updates

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#45]
- clear the fields automatically when adding another filter
- In the CorpParty detail page, the address should include city and postal code
- link company name on corp party details page to the actual company detail page

**Comment by byshine** [comment]
In the CorpParty detail page, the address should include city and postal code ->

Address is missing on `people/id`

link company name on corp party details page to the actual company detail page ->

Mocks not ready to be implemented, inconsistencies with backend

**Comment by byshine** [comment]
Update!

Address is no longer missing on `people/id`
