### ISSUE TITLE
Active and Historical Column is Blank

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#52]
http://sbc.countable.ca/#/results?advanced=true&queryString=field%3DLAST_NME%26operator%3Dcontains%26value%3Da%26field%3DFIRST_NME%26operator%3Dcontains%26value%3Da%26mode%3DANY

**Comment by byshine** [comment]
I don't see Active or Historical in the database

**Comment by countable** [comment]
@DenisCalixto can you try to track the data source down for active vs historical status of companies?

**Comment by DenisCalixto** [comment]
@byshine @countable Active and Historical states were added to Corporation and CorpParty routes.
