### ISSUE TITLE
Make corpparty detail page routable with unique URL

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#54]
http://sbc.countable.ca/#/details?ADDR_LINE_1=109%20Saskatchewan%20Blvd&APPOINTMENT_DT=2019-07-31&CESSATION_DT=2019-07-31&CORP_NME=Jean%20Coutu%20Group&CORP_NUM=7490123456&CORP_PARTY_ID=26&FIRST_NME=Jonathon&LAST_NME=Bird&MIDDLE_NME

should be details?26

**Comment by byshine** [comment]
Why details?26

**Comment by byshine** [comment]
@jvanoyen Need a key value pair, will make it details?CORP_PARTY_ID=26

**Comment by countable** [comment]
@byshine yes that's fine (FYI i made the card). probably /corpparty/26 is even better

**Comment by byshine** [comment]
Cannot complete until corp party detail search includes all the information needed 
@DenisCalixto

**Comment by countable** [comment]
@byshine don't you just need the ID of the CorpParty to make the route? What else?

**Comment by byshine** [comment]
@countable Yep, I wasn't asking him about the route.

Thanks @DenisCalixto
