### ISSUE TITLE
Provide Mock-ups Draft to Aaron and Clark (Phase II)

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#6]
For prototyping

**Comment by jvanoyen** [comment]
Here is the first iteration of screens for the Director Search: 
https://xd.adobe.com/view/ca4f7af8-bcef-4d47-5441-820822a88df4-bc7e/

The assets folder which contains the font files can be found here: https://drive.google.com/drive/folders/14n67faVjqJgRGOFRoQMqPWlokthmGTNr?usp=sharing

A note on the designing of them:
- I've followed the page styles from https://test.bcregistry.ca/cooperatives/auth
- I've also just taken the header/nav bar and bottom content directly from that page
- I've made assumptions about all of the copy, as they haven't given us any direction on that so far
- Thus, they (Jeremy, UX/UI and Loren, PO) will definitely request changes, but I didn't want to bottleneck @Aaron so hopefully this is enough to get started on
