### ISSUE TITLE
Dir Search (CorpParty): Match prototype to mockups

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#84]
Please make sure the prototype matches the mockups.
xd link: https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/

GENERAL STYLING (still working on these, xd link will be refreshed today):

- [x] White card layout added back in 
- [x] "Remove" button added back in if there are >1 filter added

SEARCH PAGE

- [x] Include TWO filter rows by default: First and Last Name
- [x] Ensure the search dropdowns match the mockups (for example, in the first one: First Name, Last Name, Middle Name, Any Name, Street Address, Postal Code, City; in the second one: Exact Match, Starts With, Ends With, Contains, Wildcard (%) )
- [x] "+Add Filter" button should be white, not the blue CTA colour
- [x] "AND/OR" dropdown is missing; default to AND.
- [x] Search button should not be aligned on the right, but next to the AND/OR dropdown, which is aligned left.
- [x] Please ensure all copy ends with punctuation (.)
- [x] Nav bar area is not up-to-date: See mockups for what should go up there ("Products" dropdown, and account name "JAMES JAMESON"
- [x] Typos in "Search Tips": No space after "Modify", and "finy" should be "find"

SEARCH RESULTS TABLE

- [x] Columns have not been changed to match mockups; some columns have been renamed, added/removed, or moved. Ex: "Filing Address" changed to "Address", "CorpParty ID" changed to "Filing #", and greyed out and moved to farthest left position.
- [x] There also should not be any blue/underlined names - the entire row should go to a Details Page when clicked.
- [x] Export button moved to top right of table (so users don't have to scroll way down)
- [x] "Inc/Org #" column name changed to "Inc/Reg #" 

DETAILS PAGE

- [x] Keep info on the right "Other examples of.." in tables with columns. These should pop down underneath the text block on the left when in mobile.
- [x] Order of information in the left text block has been changed to be more intuitive for the users - please check and make sure the prototype matches the mockups.

**Comment by byshine** [comment]
Columns have not been changed to match mockups; some columns have been renamed, added/removed, or moved. Ex: "Filing Address" changed to "Address", "CorpParty ID" changed to "Filing #", and greyed out and moved to farthest left position.

I think Clark had me change it to Filing Address. @countable Do you recall?

**Comment by byshine** [comment]
No city it looks like => https://github.com/bcgov/sbc-search/issues/68

**Comment by byshine** [comment]
There also should not be any blue/underlined names - the entire row should go to a Details Page when clicked.

Hi Julie this is not true, clicking org number goes corp detail, and the other 2 goes to corp party.

**Comment by jvanoyen** [comment]
@byshine 

"Columns have not been changed to match mockups; some columns have been renamed, added/removed, or moved. Ex: "Filing Address" changed to "Address", "CorpParty ID" changed to "Filing #", and greyed out and moved to farthest left position.

I think Clark had me change it to Filing Address. @countable Do you recall?"

The last user test (Feb 20) revealed that users do not want it to be called "Filing Address", but instead prefer "Address".

**Comment by jvanoyen** [comment]
@byshine 

"There also should not be any blue/underlined names - the entire row should go to a Details Page when clicked.

Hi Julie this is not true, clicking org number goes corp detail, and the other 2 goes to corp party." 

That (inc #) is the only blue underlined text that should remain, as it goes to a different flow (corp detail, as you said); no names in the row should be blue, or any other text. Clicking any other part of the row should go to corpparty detail.

**Comment by byshine** [comment]
I am not seeing this in the mock ups
https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/screen/59c093dd-b03e-41e9-ac0e-a6ed360e2bab/CorpParty-Search-Results-Page

**Comment by byshine** [comment]
Hi @Julie i am aware of this one 

=> Nav bar area is not up-to-date: See mockups for what should go up there ("Products" dropdown, and account name "JAMES JAMESON" 

Let's leave this one out of the checklist for now. I need to talk to the dev team as they were mentioning a standardized nav.

**Comment by byshine** [comment]
=> White card layout added back in

Looks better without.. but added back in.

**Comment by byshine** [comment]
@jvanoyen 

 Keep info on the right "Other examples of.." in tables with columns. These should pop down underneath the text block on the left when in mobile.

Tables will appaer if there is data.

**Comment by byshine** [comment]
@
