### ISSUE TITLE
Dir Search (CorpParty) Search Results Table: Choosing between Act/His, Address or None 

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#92]
The users can now choose between showing the following columns on the Director Search Results table: Active/Historical, Address, None, in order for the table to load faster.

In the CorpParty Flow xd mockups (https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/) a page has been added to show all states of the table; please do not build this page, it is for reference only.

Please note:
- [x] Act/His column and Address column are now in the same place (third column from the right side of the table), since they will never be shown at the same time, and also so the user knows where to look.
- [x] "Additional Information" blue dropdown/expanded instructions are included as well

This is likely going to change based on user input this Thursday, but for now let's do it this way so we can get feedback.

**Comment by byshine** [comment]
Done
