### ISSUE TITLE
Dir Search Prototype Validation (Tue March 3)

### ISSUE THREAD

**Issue by jvanoyen** [bcgov/sbc-search#94]
xd link: https://xd.adobe.com/view/1e4e9037-5aba-46a9-7b83-96a7fdd6146f-687f/

Please update the following to match the mockups, so we can test with users and amend accordingly:

SEARCH PAGE:
- [x] All filters should have both "Clear" buttons
- [x] All filters should have "Remove" buttons, as soon as there is more than one filter. The first filter should have it as well (remove button is currently missing on first filter).
- [x] Buttons next to filters should be consistent with the client's current button style - see mockup. They should match the inputs in height, and should be white with grey text and outline, as they are non-CTA buttons.
- [x] Suggested text for "First Name" = "John"
- [x] "Last Name" = "Smith", 
- [x] "Middle Name" = "Allan", 
- [x]  "Street Address" = "45 Sesame", 
- [x] "Postal Code" = "A1A 1A1"
- [x] Less sure what it should by for "Any Name"? Maybe a name that's commonly a first or last name, such as "James"? Could test it, anyway.

SEARCH RESULTS TABLE:
- [x] "Search Results" title above table is missing
- [x] New switching-between-columns feature

DETAILS PAGE:
- [x] Other info (on right of page) should be in table format, so it is conceptually organized similarly to the results table (since it's similar info)

**Comment by byshine** [comment]
New switching-between-columns feature => there's a diff ticket for this

**Comment by byshine** [comment]
Can you explain this one ?

Other info (on right of page) should be in table format, so it is conceptually organized similarly to the results table (since it's similar info)

It becomes a table if there is data.

**Comment by jvanoyen** [comment]
@byshine in the in the mockups it looks like this (attached). The prototype looks different, with a different layout, bolded/italic headings and no borders around the text. Please style it to match the prototype.
![Screen Shot 2020-03-03 at 2 32 09 PM](https://user-images.githubusercontent.com/37188511/75826203-d2e74380-5d5b-11ea-925c-ffb56ebef8a6.png)
